# This file was generated by GoReleaser. DO NOT EDIT.
class ChartTesting < Formula
  desc "Testing and linting Helm charts"
  homepage "https://github.com/helm/chart-testing/"
  version "3.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/helm/chart-testing/releases/download/v3.0.0/chart-testing_3.0.0_darwin_amd64.tar.gz"
    sha256 "da5a03515f4172fcd9c740173f6a2f1af294a7fd7e2dd8d8c1f6ddfdb25c66a2"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/helm/chart-testing/releases/download/v3.0.0/chart-testing_3.0.0_linux_amd64.tar.gz"
      sha256 "d0c324cb7edee0c894bb52df63cd8d5e7d85659d94e61004915c688a87d054ea"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/helm/chart-testing/releases/download/v3.0.0/chart-testing_3.0.0_linux_arm64.tar.gz"
        sha256 "d2adb56d4fcd219d8e61d3eb8e4bc1b760b62a86dbe4ede495338637da89072f"
      else
        url "https://github.com/helm/chart-testing/releases/download/v3.0.0/chart-testing_3.0.0_linux_armv6.tar.gz"
        sha256 "3c616472b8e61f83974d262ce545513c37d2b30d3ae6b23420ce7124c4324f01"
      end
    end
  end

  def install
    bin.install "ct"
    etc.install "etc" => "ct"
  end

  test do
    system "#{bin}/ct version"
  end
end
